"""initial_schema

Revision ID: 4be6afcb76ea
Revises: fd1b038262e0
Create Date: 2026-01-17 19:26:58.346748+00:00

Upgrade from fd1b038262e0
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic
revision: str = '4be6afcb76ea'
down_revision: Union[str, None] = 'fd1b038262e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_actions',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False, comment='Tenant ID for multi-tenancy'),
    sa.Column('order_id', sa.String(length=50), nullable=False, comment='Order ID from orders service'),
    sa.Column('approval_type', sa.String(length=20), nullable=False, comment='Type of approval'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='Current approval status'),
    sa.Column('order_amount', sa.Numeric(precision=12, scale=2), nullable=True, comment='Total order amount'),
    sa.Column('approved_amount', sa.Numeric(precision=12, scale=2), nullable=True, comment='Approved amount (if different from order amount)'),
    sa.Column('approver_id', sa.String(length=50), nullable=True, comment='User ID of the approver'),
    sa.Column('approver_name', sa.String(length=100), nullable=True, comment='Name of the approver'),
    sa.Column('approval_reason', sa.Text(), nullable=True, comment='Reason for approval'),
    sa.Column('rejection_reason', sa.Text(), nullable=True, comment='Reason for rejection'),
    sa.Column('customer_id', sa.String(length=50), nullable=True, comment='Customer ID for context'),
    sa.Column('customer_name', sa.String(length=200), nullable=True, comment='Customer name for context'),
    sa.Column('order_priority', sa.String(length=20), nullable=True, comment='Order priority level'),
    sa.Column('payment_type', sa.String(length=20), nullable=True, comment='Payment type'),
    sa.Column('requested_by', sa.String(length=50), nullable=False, comment='User ID who requested the approval'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True, comment='When the approval was processed'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('approval_actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approval_actions_approval_type'), ['approval_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_approval_actions_approver_id'), ['approver_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_approval_actions_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_approval_actions_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_approval_actions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_approval_actions_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('approval_audit',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('approval_action_id', sa.String(length=50), nullable=False, comment='Reference to approval action'),
    sa.Column('action', sa.String(length=50), nullable=False, comment='Action performed (created, approved, rejected, etc.)'),
    sa.Column('old_status', sa.String(length=50), nullable=True, comment='Previous status'),
    sa.Column('new_status', sa.String(length=50), nullable=True, comment='New status'),
    sa.Column('user_id', sa.String(length=50), nullable=False, comment='User ID who performed the action'),
    sa.Column('user_name', sa.String(length=100), nullable=True, comment='Name of the user'),
    sa.Column('user_role', sa.String(length=50), nullable=True, comment='Role of the user'),
    sa.Column('reason', sa.Text(), nullable=True, comment='Reason for the action'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Additional notes'),
    sa.Column('ip_address', sa.String(length=45), nullable=True, comment='IP address from which action was performed'),
    sa.Column('user_agent', sa.Text(), nullable=True, comment='User agent string'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('approval_audit', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approval_audit_approval_action_id'), ['approval_action_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_approval_audit_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_approval_audit_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('approval_audit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approval_audit_user_id'))
        batch_op.drop_index(batch_op.f('ix_approval_audit_created_at'))
        batch_op.drop_index(batch_op.f('ix_approval_audit_approval_action_id'))

    op.drop_table('approval_audit')
    with op.batch_alter_table('approval_actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approval_actions_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_approval_actions_status'))
        batch_op.drop_index(batch_op.f('ix_approval_actions_order_id'))
        batch_op.drop_index(batch_op.f('ix_approval_actions_is_active'))
        batch_op.drop_index(batch_op.f('ix_approval_actions_approver_id'))
        batch_op.drop_index(batch_op.f('ix_approval_actions_approval_type'))

    op.drop_table('approval_actions')
    # ### end Alembic commands ###
