"""Initial schema

Revision ID: 54b5b824fe2c
Revises: 
Create Date: 2026-01-17 14:12:49.855933+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic
revision: str = '54b5b824fe2c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create all tables WITHOUT foreign key constraints first to avoid circular dependencies
    op.create_table('permissions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('resource', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tenants',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('settings', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('admin_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('admin_id'),
    sa.UniqueConstraint('domain')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('login_attempts', sa.Integer(), nullable=True),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_email', 'users', ['email'], unique=False)

    op.create_table('refresh_tokens',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_table('role_permissions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )

    # Now add all foreign key constraints after all tables exist
    op.create_foreign_key(
        'fk_roles_tenant_id', 'roles', 'tenants',
        ['tenant_id'], ['id']
    )
    op.create_foreign_key(
        'fk_tenants_admin_id', 'tenants', 'users',
        ['admin_id'], ['id']
    )
    op.create_foreign_key(
        'fk_users_role_id', 'users', 'roles',
        ['role_id'], ['id']
    )
    op.create_foreign_key(
        'fk_users_tenant_id', 'users', 'tenants',
        ['tenant_id'], ['id']
    )
    op.create_foreign_key(
        'fk_refresh_tokens_user_id', 'refresh_tokens', 'users',
        ['user_id'], ['id']
    )
    op.create_foreign_key(
        'fk_role_permissions_role_id', 'role_permissions', 'roles',
        ['role_id'], ['id']
    )
    op.create_foreign_key(
        'fk_role_permissions_permission_id', 'role_permissions', 'permissions',
        ['permission_id'], ['id']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop foreign keys first (in reverse order)
    op.drop_constraint('fk_role_permissions_permission_id', 'role_permissions', type_='foreignkey')
    op.drop_constraint('fk_role_permissions_role_id', 'role_permissions', type_='foreignkey')
    op.drop_constraint('fk_refresh_tokens_user_id', 'refresh_tokens', type_='foreignkey')
    op.drop_constraint('fk_users_tenant_id', 'users', type_='foreignkey')
    op.drop_constraint('fk_users_role_id', 'users', type_='foreignkey')
    op.drop_constraint('fk_tenants_admin_id', 'tenants', type_='foreignkey')
    op.drop_constraint('fk_roles_tenant_id', 'roles', type_='foreignkey')

    # Then drop tables
    op.drop_table('role_permissions')
    op.drop_table('refresh_tokens')
    op.drop_index('ix_users_email', 'users')
    op.drop_table('users')
    op.drop_table('tenants')
    op.drop_table('roles')
    op.drop_table('permissions')
    # ### end Alembic commands ###
