"""
Security module for TMS Service
"""
from .auth import TokenData, verify_token, extract_token_from_header
from .dependencies import (
    get_current_token_data,
    require_permissions,
    require_any_permission,
    require_tenant_access,
    get_current_tenant_id,
    get_current_user_id,
    is_active_user,
    # TMS-specific permissions
    TRIP_READ,
    TRIP_READ_ALL,
    TRIP_CREATE,
    TRIP_UPDATE,
    TRIP_DELETE,
    TRIP_ASSIGN,
    TRIP_TRACK,
    ORDER_SPLIT,
    ORDER_REASSIGN,
    RESOURCES_READ,
    RESOURCES_READ_ALL,
    DRIVERS_ASSIGN,
    VEHICLES_TRACK,
    ROUTES_CREATE,
    ROUTES_OPTIMIZE,
    SCHEDULES_READ,
    SCHEDULES_UPDATE,
)

__all__ = [
    "TokenData",
    "verify_token",
    "extract_token_from_header",
    "get_current_token_data",
    "require_permissions",
    "require_any_permission",
    "require_tenant_access",
    "get_current_tenant_id",
    "get_current_user_id",
    "is_active_user",
    "TRIP_READ",
    "TRIP_READ_ALL",
    "TRIP_CREATE",
    "TRIP_UPDATE",
    "TRIP_DELETE",
    "TRIP_ASSIGN",
    "TRIP_TRACK",
    "ORDER_SPLIT",
    "ORDER_REASSIGN",
    "RESOURCES_READ",
    "RESOURCES_READ_ALL",
    "DRIVERS_ASSIGN",
    "VEHICLES_TRACK",
    "ROUTES_CREATE",
    "ROUTES_OPTIMIZE",
    "SCHEDULES_READ",
    "SCHEDULES_UPDATE",
]