"""initial_schema

Revision ID: 547145b13cbb
Revises: c60d0470c4cd
Create Date: 2026-01-17 19:24:42.607785+00:00

Upgrade from c60d0470c4cd
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic
revision: str = '547145b13cbb'
down_revision: Union[str, None] = 'c60d0470c4cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('order_number', sa.String(length=50), nullable=False),
    sa.Column('tenant_id', sa.String(length=255), nullable=False, comment='Tenant ID - references tenant in auth database'),
    sa.Column('customer_id', sa.String(length=255), nullable=False, comment='Customer ID from customer service'),
    sa.Column('branch_id', sa.String(length=255), nullable=False, comment='Branch ID from branch service'),
    sa.Column('order_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('tms_order_status', sa.String(length=50), nullable=True),
    sa.Column('items_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('remaining_items_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('pickup_address', sa.Text(), nullable=True),
    sa.Column('pickup_contact_name', sa.String(length=100), nullable=True),
    sa.Column('pickup_contact_phone', sa.String(length=20), nullable=True),
    sa.Column('pickup_city', sa.String(length=100), nullable=True),
    sa.Column('pickup_state', sa.String(length=100), nullable=True),
    sa.Column('pickup_pincode', sa.String(length=20), nullable=True),
    sa.Column('delivery_address', sa.Text(), nullable=True),
    sa.Column('delivery_contact_name', sa.String(length=100), nullable=True),
    sa.Column('delivery_contact_phone', sa.String(length=20), nullable=True),
    sa.Column('delivery_city', sa.String(length=100), nullable=True),
    sa.Column('delivery_state', sa.String(length=100), nullable=True),
    sa.Column('delivery_pincode', sa.String(length=20), nullable=True),
    sa.Column('total_weight', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_volume', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('package_count', sa.Integer(), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('payment_type', sa.String(length=20), nullable=True),
    sa.Column('special_instructions', sa.Text(), nullable=True),
    sa.Column('delivery_instructions', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=False, comment='User ID who created the order'),
    sa.Column('updated_by', sa.String(length=255), nullable=True, comment='User ID who last updated the order'),
    sa.Column('finance_approved_by', sa.String(length=255), nullable=True, comment='User ID who approved in finance'),
    sa.Column('logistics_approved_by', sa.String(length=255), nullable=True, comment='User ID who approved in logistics'),
    sa.Column('driver_id', sa.String(length=255), nullable=True, comment='Driver ID assigned to this order'),
    sa.Column('trip_id', sa.String(length=255), nullable=True, comment='Trip ID from TMS service'),
    sa.Column('pickup_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivery_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finance_approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('logistics_approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('picked_up_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finance_rejected_reason', sa.Text(), nullable=True),
    sa.Column('logistics_rejected_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_driver_id'), ['driver_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_order_number'), ['order_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_orders_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_tms_order_status'), ['tms_order_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_trip_id'), ['trip_id'], unique=False)

    op.create_table('order_documents',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('order_id', sa.String(length=255), nullable=False),
    sa.Column('uploaded_by', sa.String(length=255), nullable=False, comment='User ID who uploaded the document'),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=True, comment='SHA-256 hash of the file'),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('verified_by', sa.String(length=255), nullable=True, comment='User ID who verified the document'),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verification_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_documents_file_hash'), ['file_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_documents_order_id'), ['order_id'], unique=False)

    op.create_table('order_items',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('order_id', sa.String(length=255), nullable=False),
    sa.Column('product_id', sa.String(length=255), nullable=False, comment='Product ID from product service'),
    sa.Column('product_name', sa.String(length=200), nullable=False),
    sa.Column('product_code', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('weight', sa.Numeric(precision=10, scale=2), nullable=True, comment='Weight per unit'),
    sa.Column('volume', sa.Numeric(precision=10, scale=2), nullable=True, comment='Volume per unit'),
    sa.Column('dimensions_length', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('dimensions_width', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('dimensions_height', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('item_status', sa.String(length=50), nullable=True, comment='Item status: pending_to_assign, planning, loading, on_route, delivered, failed, returned'),
    sa.Column('trip_id', sa.String(length=255), nullable=True, comment='ID of the trip this item is assigned to (from TMS service)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_items_item_status'), ['item_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_items_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_items_trip_id'), ['trip_id'], unique=False)

    op.create_table('order_status_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.String(length=255), nullable=False),
    sa.Column('changed_by', sa.String(length=255), nullable=False, comment='User ID who changed the status'),
    sa.Column('from_status', sa.String(length=50), nullable=True),
    sa.Column('to_status', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order_status_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_status_history_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_status_history_order_id'), ['order_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_status_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_status_history_order_id'))
        batch_op.drop_index(batch_op.f('ix_order_status_history_created_at'))

    op.drop_table('order_status_history')
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_items_trip_id'))
        batch_op.drop_index(batch_op.f('ix_order_items_order_id'))
        batch_op.drop_index(batch_op.f('ix_order_items_item_status'))

    op.drop_table('order_items')
    with op.batch_alter_table('order_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_documents_order_id'))
        batch_op.drop_index(batch_op.f('ix_order_documents_file_hash'))

    op.drop_table('order_documents')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_trip_id'))
        batch_op.drop_index(batch_op.f('ix_orders_tms_order_status'))
        batch_op.drop_index(batch_op.f('ix_orders_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_orders_status'))
        batch_op.drop_index(batch_op.f('ix_orders_order_number'))
        batch_op.drop_index(batch_op.f('ix_orders_is_active'))
        batch_op.drop_index(batch_op.f('ix_orders_driver_id'))
        batch_op.drop_index(batch_op.f('ix_orders_customer_id'))
        batch_op.drop_index(batch_op.f('ix_orders_branch_id'))

    op.drop_table('orders')
    # ### end Alembic commands ###
