"""Initial schema

Revision ID: e4da6912e9bc
Revises: 
Create Date: 2026-01-17 14:17:15.717783+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic
revision: str = 'e4da6912e9bc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tms_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('company_id', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('module', sa.String(length=50), nullable=False),
    sa.Column('record_id', sa.String(length=50), nullable=True),
    sa.Column('record_type', sa.String(length=50), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tms_audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tms_audit_logs_id'), ['id'], unique=False)

    op.create_table('trips',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('company_id', sa.String(length=50), nullable=False),
    sa.Column('branch', sa.String(length=100), nullable=False),
    sa.Column('truck_plate', sa.String(length=20), nullable=False),
    sa.Column('truck_model', sa.String(length=100), nullable=False),
    sa.Column('truck_capacity', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.String(length=50), nullable=False),
    sa.Column('driver_name', sa.String(length=100), nullable=False),
    sa.Column('driver_phone', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('origin', sa.String(length=100), nullable=True),
    sa.Column('destination', sa.String(length=100), nullable=True),
    sa.Column('distance', sa.Integer(), nullable=True),
    sa.Column('estimated_duration', sa.Integer(), nullable=True),
    sa.Column('pre_trip_time', sa.Integer(), nullable=True),
    sa.Column('post_trip_time', sa.Integer(), nullable=True),
    sa.Column('capacity_used', sa.Integer(), nullable=True),
    sa.Column('capacity_total', sa.Integer(), nullable=False),
    sa.Column('trip_date', sa.Date(), nullable=False),
    sa.Column('maintenance_note', sa.Text(), nullable=True),
    sa.Column('paused_at', sa.DateTime(), nullable=True),
    sa.Column('paused_reason', sa.String(length=500), nullable=True),
    sa.Column('resumed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trip_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('company_id', sa.String(length=50), nullable=False),
    sa.Column('order_id', sa.String(length=50), nullable=False),
    sa.Column('customer', sa.String(length=200), nullable=False),
    sa.Column('customer_address', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('tms_order_status', sa.String(length=50), nullable=True),
    sa.Column('item_status', sa.String(length=50), nullable=True),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('items', sa.Integer(), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('delivery_status', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('original_order_id', sa.String(length=50), nullable=True),
    sa.Column('original_items', sa.Integer(), nullable=True),
    sa.Column('original_weight', sa.Float(), nullable=True),
    sa.Column('items_json', sa.JSON(), nullable=True),
    sa.Column('remaining_items_json', sa.JSON(), nullable=True),
    sa.Column('customer_contact', sa.String(length=200), nullable=True),
    sa.Column('customer_phone', sa.String(length=50), nullable=True),
    sa.Column('product_name', sa.String(length=200), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('special_instructions', sa.Text(), nullable=True),
    sa.Column('delivery_instructions', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trip_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trip_orders_id'), ['id'], unique=False)

    op.create_table('trip_routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('company_id', sa.String(length=50), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('estimated_arrival', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['trip_orders.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trip_routes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trip_routes_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip_routes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trip_routes_id'))

    op.drop_table('trip_routes')
    with op.batch_alter_table('trip_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trip_orders_id'))

    op.drop_table('trip_orders')
    op.drop_table('trips')
    with op.batch_alter_table('tms_audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tms_audit_logs_id'))

    op.drop_table('tms_audit_logs')
    # ### end Alembic commands ###
